// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2.Data;

#nullable disable

namespace refactorbackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250825055642_InitAuthSchema")]
    partial class InitAuthSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OpexGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OpexID")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OpexID");

                    b.ToTable("OpexGroup", "Planning_Realization");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("WebApplication2.Models.Human.BNU", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BulanTahun")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DivisiDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JumlahPerserta")
                        .HasColumnType("int");

                    b.Property<string>("SentralDesentral")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsulanTraining")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("BNU", "Human_Training");
                });

            modelBuilder.Entity("WebApplication2.Models.Human.FTE", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NPP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Posisi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("FTE", "Human_Resource");
                });

            modelBuilder.Entity("WebApplication2.Models.Human.InternalTraining", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal?>("Biaya")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BulanTahun")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DivisiDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JumlahPerserta")
                        .HasColumnType("int");

                    b.Property<string>("UsulanTraining")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("InternalTraining", "Human_Training");
                });

            modelBuilder.Entity("WebApplication2.Models.Human.KebutuhanFTE", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Existing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kebutuhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Posisi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("KebutuhanFTE", "Human_Resource");
                });

            modelBuilder.Entity("WebApplication2.Models.Human.KompetensiPegawai", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JudulTraining")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NPP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SertifikasiNonSerifikasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TahunPelaksanaan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("KompetensiPegawai", "Human_Training");
                });

            modelBuilder.Entity("WebApplication2.Models.Human.NonFTE", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMPCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FirstDayWork")
                        .HasColumnType("datetime2");

                    b.Property<string>("JNKEL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Job")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NPP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vendor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("NonFTE", "Human_Resource");
                });

            modelBuilder.Entity("WebApplication2.Models.Planning.BusinessPlan.HorizontalMatrix", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DivisiService")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dukungan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InisiatifID")
                        .HasColumnType("int");

                    b.Property<string>("KeyIndicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetPemenuhanHA")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("InisiatifID");

                    b.ToTable("HorizontalMatrix", "Planning_BusinessPlan");
                });

            modelBuilder.Entity("WebApplication2.Models.Planning.BusinessPlan.InfoUnit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("InfoUnit", "Planning_BusinessPlan");
                });

            modelBuilder.Entity("WebApplication2.Models.Planning.BusinessPlan.Inisiatif", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("InisiatifStrategi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodeSS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodeSaranStrategiBNI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformanceIndicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Perspektif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosCapex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosOpex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Q1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Q2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Q3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Q4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RpCapex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RpOpex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Satuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Target2025")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UIC")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Inisiatif", "Planning_BusinessPlan");
                });

            modelBuilder.Entity("WebApplication2.Models.Planning.BusinessPlan.ListStrategy", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal?>("Alignment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ComplexityOfEffort")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DampakFinance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FinalScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ListStrategi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ListStrategy", "Planning_BusinessPlan");
                });

            modelBuilder.Entity("WebApplication2.Models.Planning.BusinessPlan.MapDiagram", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("XmlData")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("MapDiagram", "Planning_BusinessPlan");
                });

            modelBuilder.Entity("WebApplication2.Models.Planning.BusinessPlan.PI", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("InisiatifID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("InisiatifID");

                    b.ToTable("PI", "Planning_BusinessPlan");
                });

            modelBuilder.Entity("WebApplication2.Models.Planning.BusinessPlan.SDMManPower", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ExistingPeople")
                        .HasColumnType("int");

                    b.Property<string>("Gap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JumlahKebutuhanWLA")
                        .HasColumnType("int");

                    b.Property<string>("LevelGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Positions")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("SDMManPower", "Planning_BusinessPlan");
                });

            modelBuilder.Entity("WebApplication2.Models.Planning.BusinessPlan.SDMPelatihan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descriptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Periode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProposedTraining")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedStrategy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Timeline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypePlan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("SDMPelatihan", "Planning_BusinessPlan");
                });

            modelBuilder.Entity("WebApplication2.Models.Planning.BusinessPlan.UsulanCapex", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AnggaranDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MataAnggaran")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Nilai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Statuss")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeAnggaran")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("UsulanCapex", "Planning_BusinessPlan");
                });

            modelBuilder.Entity("WebApplication2.Models.Planning.BusinessPlan.UsulanOpex", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AnggaranDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MataAnggaran")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Nilai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Statuss")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeAnggaran")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("UsulanOpex", "Planning_BusinessPlan");
                });

            modelBuilder.Entity("WebApplication2.Models.Planning.Realization.Opex", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal?>("Apr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Aug")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DataTimeFrom")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Dec")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Dec2023")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Dec2024")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Feb")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FullYear")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Jan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Jul")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Jun")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Mar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MataAnggaran")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("May")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Nov")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Oct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<decimal?>("PercentGrowth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RpGrowth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Sep")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SisaAnggaransdFY")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("YTD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("toAng2024")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("toAngYTD2024")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Opex", "Planning_Realization");
                });

            modelBuilder.Entity("WebApplication2.Models.Procurement.APS", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AfterDivision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ContractDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContractNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ContractValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoMemoAPSKePFA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PIC_PFA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PKSDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PKSNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SPKDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SPKNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuratPenetapanPemenang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuratPenunjukanPekerjaan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Term1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfBudget")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfProcurement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vendor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("WaktuTerm1")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("APS", "Procurement");
                });

            modelBuilder.Entity("WebApplication2.Models.Procurement.StatusPengadaan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("APSID")
                        .HasColumnType("int");

                    b.Property<string>("AlurPengadaan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<string>("Persetujuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("APSID");

                    b.HasIndex("ParentID");

                    b.ToTable("StatusPengadaan", "Procurement");
                });

            modelBuilder.Entity("refactorbackend.Dtos.NewFolder.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("FileContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("refactorbackend.Models.Planning.Realization.Capex.CapexBangunan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AsetHakGuna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KategoriInvestasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaProyek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NilaiKontrakSPK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Realisasi2025")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Realisasi2026")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Realisasi2027")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Realisasi2028")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SektorPengusul")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitPengusul")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CapexBangunan", "Planning_Realization");
                });

            modelBuilder.Entity("refactorbackend.Models.Planning.Realization.Capex.CapexKendaraan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AsetHakGuna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupKP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaProyek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NilaiKontrakSPK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Realisasi2025")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Realisasi2026")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Realisasi2027")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Realisasi2028")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RincianEntitas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoadmapInisiative")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SektorPengusul")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Unit")
                        .HasColumnType("int");

                    b.Property<string>("UnitPengusul")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CapexKendaraan", "Planning_Realization");
                });

            modelBuilder.Entity("refactorbackend.Models.Planning.Realization.Capex.CapexNonOtomasi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AsetHakGuna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaProyek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NilaiKontrakSPK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Realisasi2025")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Realisasi2026")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Realisasi2027")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Realisasi2028")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RincianEntitas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SektorPengusul")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Unit")
                        .HasColumnType("int");

                    b.Property<string>("UnitPengusul")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CapexNonOtomasi", "Planning_Realization");
                });

            modelBuilder.Entity("refactorbackend.Models.Planning.Realization.Capex.CapexOA", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("NamaProyek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NilaiKontrakSPK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Realisasi2025")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Realisasi2026")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Realisasi2027")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Realisasi2028")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RincianEntitas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SektorPengusul")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Unit")
                        .HasColumnType("int");

                    b.Property<string>("UnitPengusul")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CapexOA", "Planning_Realization");
                });

            modelBuilder.Entity("refactorbackend.Models.Planning.Realization.Capex.CapexOtomasi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AsetHakGuna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DivisiOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupKP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NIlaiKontrakSPK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NamaProyek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoFS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Q1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Realisasi2025")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Realisasi2026")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Realisasi2027")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Realisasi2028")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SektorOwner")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CapexOtomasi", "Planning_Realization");
                });

            modelBuilder.Entity("refactorbackend.Models.Procurement.APSLogTrail", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<int>("APSID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogID");

                    b.HasIndex("APSID");

                    b.ToTable("APSLogtrail", "Procurement");
                });

            modelBuilder.Entity("refactorbackend.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("OpexGroup", b =>
                {
                    b.HasOne("WebApplication2.Models.Planning.Realization.Opex", "Opex")
                        .WithMany("OpexGroups")
                        .HasForeignKey("OpexID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opex");
                });

            modelBuilder.Entity("WebApplication2.Models.Planning.BusinessPlan.HorizontalMatrix", b =>
                {
                    b.HasOne("WebApplication2.Models.Planning.BusinessPlan.Inisiatif", "Inisiatif")
                        .WithMany("HorizontalMatrices")
                        .HasForeignKey("InisiatifID");

                    b.Navigation("Inisiatif");
                });

            modelBuilder.Entity("WebApplication2.Models.Planning.BusinessPlan.PI", b =>
                {
                    b.HasOne("WebApplication2.Models.Planning.BusinessPlan.Inisiatif", "Inisiatif")
                        .WithMany("PIs")
                        .HasForeignKey("InisiatifID");

                    b.Navigation("Inisiatif");
                });

            modelBuilder.Entity("WebApplication2.Models.Procurement.StatusPengadaan", b =>
                {
                    b.HasOne("WebApplication2.Models.Procurement.APS", "APS")
                        .WithMany("StatusPengadaan")
                        .HasForeignKey("APSID");

                    b.HasOne("WebApplication2.Models.Procurement.StatusPengadaan", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentID");

                    b.Navigation("APS");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("refactorbackend.Models.Procurement.APSLogTrail", b =>
                {
                    b.HasOne("WebApplication2.Models.Procurement.APS", "APS")
                        .WithMany("APSLogTrail")
                        .HasForeignKey("APSID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("APS");
                });

            modelBuilder.Entity("refactorbackend.Models.RefreshToken", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication2.Models.Planning.BusinessPlan.Inisiatif", b =>
                {
                    b.Navigation("HorizontalMatrices");

                    b.Navigation("PIs");
                });

            modelBuilder.Entity("WebApplication2.Models.Planning.Realization.Opex", b =>
                {
                    b.Navigation("OpexGroups");
                });

            modelBuilder.Entity("WebApplication2.Models.Procurement.APS", b =>
                {
                    b.Navigation("APSLogTrail");

                    b.Navigation("StatusPengadaan");
                });

            modelBuilder.Entity("WebApplication2.Models.Procurement.StatusPengadaan", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
